import{a as w,S,i as d}from"./assets/vendor-BDaiwwc1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const C="https://pixabay.com",v="/api";async function h(s,t,a){const o=new URLSearchParams({key:"48827773-420cc6a3931f90379a2431d96",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:a,page:t}),e=C+v+`?${o}`;return(await w.get(e)).data}const x=new S(".gallery a",{captionsData:"alt",captionDelay:250,close:"true"});function p(s){const t=document.querySelector(".gallery"),a=s.map(o=>`<li class="gallery-item">
            <a class='gallery-link' href="${o.largeImageURL}">
              <img class="li-img"
              src="${o.webformatURL}" 
              alt="${o.tags}/> 
              <div class="li-text">
                <table class="table">
                    <tr><td>Likes</td><td>Views</td><td>Comment</td><td>Downloads</tr>
                    <tr><td>>${o.likes}</td><td>${o.views}</td><td>${o.comments}</td><td>${o.downloads}</tr>
                </table>
              
                </div>
              </a>
            </li>
            
    `).join("");t.insertAdjacentHTML("beforeend",a),x.refresh()}const f=document.querySelector(".form"),q=document.querySelector(".input-search"),c=document.querySelector(".wait-msg"),u=document.querySelector(".load-btn"),m=document.querySelector(".load-msg");let i="",n=null,y=1,g=40;f.addEventListener("submit",async s=>{if(s.preventDefault(),document.querySelector(".gallery").innerHTML="",i=q.value.trim(),n=1,!i){d.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:"true",position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Input search string"});return}c.innerHTML='"Wait, the image is loaded" <span class="loader"></span>';try{const t=await h(i,n,g);p(t.hits),y=t.total,t.hits.length==0&&d.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:"true",position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:"Sorry, there are no images matching your search query. Please try again!"})}catch{c.textContent="Ups ..."}c.textContent="",b(),f.reset()});u.addEventListener("click",async()=>{L(),m.innerHTML='"Wait, the image is loaded" <span class="loader"></span>',n+=1,b();const s=await h(i,n,g);p(s.hits),m.textContent="",M()});function b(){const s=Math.ceil(y/g);n>=s?(L(),d.show({backgroundColor:"rgba(239, 64, 64, 1)",messageColor:"rgba(255, 255, 255, 1)",close:"true",position:"topRight",titleColor:"#fff",titleSize:"16px",message:"We are sorry, but you have reached the end of search results."})):P()}function P(){u.classList.remove("hidden")}function L(){u.classList.add("hidden")}function M(){const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:2*t})}
//# sourceMappingURL=index.js.map
